baseURL: 'http://sfprivg7qec6tdle7u6hdepzjibin6fn3ivm6qlwytr235rh5vc6bfqd.onion/'
publishDir: tor
languageCode: en-us
title: blog.sethforprivacy.com
theme: terminal
paginate: 10
enableGitInfo: true
params:
  contentTypeName: posts
  themeColor: orange
  showMenuItems: 7
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true
  favicon: favicon.ico
  showLastUpdated: true
  oneHeadingSize: false
  twitter:
    creator: sethforprivacy
    site: sethforprivacy
languages:
  en:
    languageName: English
    title: blog.sethforprivacy.com
    subtitle: 'A simple blog about privacy, Monero, and self-hosting'
    owner: Seth For Privacy
    keywords: ''
    copyright: ''
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page
    params:
      logo:
        logoText: blog.sethforprivacy.com
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: About Me
          url: /about
        - identifier: posts
          name: Posts
          url: /posts
        - identifier: guides
          name: Guides
          url: /guides
        - identifier: resources
          name: Hosted Resources
          url: /about/#my-community-resources
        - identifier: rss
          name: RSS Feed
          url: /index.xml
        - identifier: podcast
          name: Opt Out Podcast
          url: /episodes
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: false
    disable: true
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: true
  vimeo:
    disable: true
    enableDNT: false
    simple: false
  youtube:
    disable: true
    privacyEnhanced: false
markup:
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true
