baseURL: 'http://sfprivg7qec6tdle7u6hdepzjibin6fn3ivm6qlwytr235rh5vc6bfqd.onion/'
publishDir: tor
languageCode: en-us
title: blog.sethforprivacy.com
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  # env: production
  title: blog.sethforprivacy.com
  description: "A simple blog about privacy, Monero, and self-hosting"
  author: sethforprivacy
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  mainSections: posts

  assets:
    disableHLJS: true
    # disableFingerprinting: true

  label:
    text: "Home"
    icon: /favicon.ico
    iconHeight: 35
  
  homeInfoParams:
    Title: "Welcome to Seth For Privacy's blog! \U0001F44B"
    Content: >
      - Take a look at "Posts" for blog posts, "Guides" for guides on self-hosting and Monero, and "Opt Out Podcast" for content related to Opt Out.

      - ***To contact me, use one of the methods below or [an alternative](/about/#how-to-contact-me).***

  socialIcons:
    - name: email
      url: "mailto:seth@sethforprivacy.com"
    - name: twitter
      url: "https://twitter.com/sethforprivacy"
    - name: matrix
      url: "https://matrix.to/#/@sethsimmons:monero.social"
    - name: reddit
      url: "https://www.reddit.com/user/fort3hlulz"
    - name: github
      url: "https://github.com/sethforprivacy"
    - name: rss
      url: "/index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/sethforprivacy/sethforprivacy.com/blob/master/content"
    Text: "Suggest Changes To This Post" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: 1
    - identifier: guides
      name: Guides
      url: /guides
      weight: 2
    - identifier: resources
      name: Hosted Resources
      url: /about/#my-community-resources
      weight: 3
    - identifier: podcast
      name: Opt Out Podcast
      url: /episodes
      weight: 4
    - identifier: about
      name: About Me
      url: /about
      weight: 5
    - identifier: search
      name: Search
      url: /search
      weight: 6

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: false
    disable: true
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: false
    enableDNT: false
    simple: true
  vimeo:
    disable: true
    enableDNT: false
    simple: false
  youtube:
    disable: true
    privacyEnhanced: false
markup:
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    # noClasses: false
    style: dracula
