name: Build site and deploy custom image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build clearnet
        run: hugo --minify --config $GITHUB_WORKSPACE/clearnet_config.yml --destination $GITHUB_WORKSPACE/public

      - name: Build Tor
        run: hugo --minify --config $GITHUB_WORKSPACE/tor_config.yml --destination $GITHUB_WORKSPACE/tor

      - name: Build and push to Docker Hub and Github Packages Docker Registry
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sethforprivacy-blog:latest
            ${{ secrets.DOCKER_USERNAME }}/sethforprivacy-blog:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
      - name: Scan new image and output results
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ secrets.DOCKER_USERNAME }}/sethforprivacy-blog:latest
          severity-threshold: HIGH
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
